{% set name = "superpunto" %}
{% set version = "5.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/RaulPPelaez/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: ee4fcf85f64ed42b6f6971c7592de96004fce1e41caf9a36863dcd00b50b5ea5

build:
  script: |
    cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=$PREFIX -G Ninja .
    cmake --build .
    cmake --install .
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake >=3.20
    - jinja2
    - ninja
  host:
    - libopengl
    - sdl2
    - sdl2_ttf
    - glew
    - libpng
    - libopengl-devel
    - libglx-devel
    - zlib
    - libgl-devel
test:
  commands:
    # Make sure the spunto command is available, we cannot run it because it requires a display
    - which spunto

about:
  home: https://github.com/RaulPPelaez/superpunto/
  summary: 'A particle visualizator'
  description: |
    Superpunto is a fast sphere visualizer with superb light effects written in OpenGL 4.5. Via a simple format (similar to the XYZ format) one can visualize the trajectories of a large number of spherical particles in an interactive way.
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  dev_url: https://github.com/RaulPPelaez/superpunto/

extra:
  recipe-maintainers:
    - RaulPPelaez
